//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "PageHeader.xaml.h"

void ::RenderEngine::Controls::PageHeader::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///PageHeader.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::RenderEngine::Controls::PageHeader, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    PageHeader_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // PageHeader.xaml line 11
                this->obj2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 4: // PageHeader.xaml line 13
                this->obj4 = safe_cast<::Windows::UI::Xaml::Controls::ContentPresenter^>(__target);
                break;
        }
    }

    void Disable(int lineNumber, int columnNumber)
    {
        if (lineNumber == 11 && columnNumber == 25)
        {
            isobj2BackgroundDisabled = true;
        }
        else if (lineNumber == 15 && columnNumber == 17)
        {
            isobj4VerticalAlignmentDisabled = true;
        }
        else if (lineNumber == 16 && columnNumber == 17)
        {
            isobj4HorizontalAlignmentDisabled = true;
        }
        else if (lineNumber == 17 && columnNumber == 17)
        {
            isobj4MarginDisabled = true;
        }
        else if (lineNumber == 18 && columnNumber == 17)
        {
            isobj4ContentDisabled = true;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        throw ref new ::Platform::NotImplementedException();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        throw ref new ::Platform::NotImplementedException();
    }

private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::Grid^ obj2;
    ::Windows::UI::Xaml::Controls::ContentPresenter^ obj4;

    // Static fields for each binding's enabled/disabled state
    static bool isobj2BackgroundDisabled;
    static bool isobj4VerticalAlignmentDisabled;
    static bool isobj4HorizontalAlignmentDisabled;
    static bool isobj4MarginDisabled;
    static bool isobj4ContentDisabled;

    // Update methods for each path node used in binding steps.
    void Update_(::RenderEngine::Controls::PageHeader^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Background(obj->Background, phase);
                this->Update_VerticalContentAlignment(obj->VerticalContentAlignment, phase);
                this->Update_HorizontalContentAlignment(obj->HorizontalContentAlignment, phase);
                this->Update_Padding(obj->Padding, phase);
                this->Update_HeaderContent(obj->HeaderContent, phase);
            }
        }
    }
    void Update_Background(::Windows::UI::Xaml::Media::Brush^ obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // PageHeader.xaml line 11
            if (!isobj2BackgroundDisabled)
            {
                Set_Windows_UI_Xaml_Controls_Panel_Background(this->obj2, obj, nullptr);
            }
        }
    }
    void Update_VerticalContentAlignment(::Windows::UI::Xaml::VerticalAlignment obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // PageHeader.xaml line 13
            if (!isobj4VerticalAlignmentDisabled)
            {
                Set_Windows_UI_Xaml_FrameworkElement_VerticalAlignment(this->obj4, obj);
            }
        }
    }
    void Update_HorizontalContentAlignment(::Windows::UI::Xaml::HorizontalAlignment obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // PageHeader.xaml line 13
            if (!isobj4HorizontalAlignmentDisabled)
            {
                Set_Windows_UI_Xaml_FrameworkElement_HorizontalAlignment(this->obj4, obj);
            }
        }
    }
    void Update_Padding(::Windows::UI::Xaml::Thickness obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // PageHeader.xaml line 13
            if (!isobj4MarginDisabled)
            {
                Set_Windows_UI_Xaml_FrameworkElement_Margin(this->obj4, obj);
            }
        }
    }
    void Update_HeaderContent(::Windows::UI::Xaml::UIElement^ obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // PageHeader.xaml line 13
            if (!isobj4ContentDisabled)
            {
                Set_Windows_UI_Xaml_Controls_ContentPresenter_Content(this->obj4, obj, nullptr);
            }
        }
    }
    static void Set_Windows_UI_Xaml_Controls_Panel_Background(::Windows::UI::Xaml::Controls::Panel^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Background = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_VerticalAlignment(::Windows::UI::Xaml::FrameworkElement^ obj, ::Windows::UI::Xaml::VerticalAlignment value)
    {
        obj->VerticalAlignment = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_HorizontalAlignment(::Windows::UI::Xaml::FrameworkElement^ obj, ::Windows::UI::Xaml::HorizontalAlignment value)
    {
        obj->HorizontalAlignment = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_Margin(::Windows::UI::Xaml::FrameworkElement^ obj, ::Windows::UI::Xaml::Thickness value)
    {
        obj->Margin = value;
    }
    static void Set_Windows_UI_Xaml_Controls_ContentPresenter_Content(::Windows::UI::Xaml::Controls::ContentPresenter^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Content = value;
    }
};

    // Initializing static fields for each binding's enabled/disabled state
bool RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings::isobj2BackgroundDisabled = false;
bool RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings::isobj4VerticalAlignmentDisabled = false;
bool RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings::isobj4HorizontalAlignmentDisabled = false;
bool RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings::isobj4MarginDisabled = false;
bool RenderEngine::Controls::PageHeader::PageHeader_obj1_Bindings::isobj4ContentDisabled = false;

void ::RenderEngine::Controls::PageHeader::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->grid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->titleBar = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 4:
        {
            this->content = safe_cast<::Windows::UI::Xaml::Controls::ContentPresenter^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::RenderEngine::Controls::PageHeader::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // PageHeader.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
                PageHeader_obj1_Bindings* objBindings = new PageHeader_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element1, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


