//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "BasicPage.xaml.h"
#include "Distributions.xaml.h"
#include "FinancialChart.xaml.h"
#include "LandingPage.xaml.h"
#include "MovingAverage.xaml.h"
#include "PageHeader.xaml.h"
#include "App.xaml.h"
#include "AppShell.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "BasicPage.g.hpp"
#include "Distributions.g.hpp"
#include "FinancialChart.g.hpp"
#include "LandingPage.g.hpp"
#include "MovingAverage.g.hpp"
#include "PageHeader.g.hpp"
#include "App.g.hpp"
#include "AppShell.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_DataType(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->DataType);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Type(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Type);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Dpi(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Dpi);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_UseSharedDevice(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->UseSharedDevice);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_ForceSoftwareRenderer(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->ForceSoftwareRenderer);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_DpiScale(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->DpiScale);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_ClearColor(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->ClearColor);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_ReadyToDraw(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->ReadyToDraw);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Size(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Size);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_AppFrame(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->AppFrame;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_RenderCommand(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->RenderCommand;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_DistributionTypes(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->DistributionTypes;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_HeaderContent(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->HeaderContent;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_ViewModel(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->ViewModel;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Device(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Device;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_CustomDevice(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->CustomDevice;
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_DataType(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->DataType = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_UseSharedDevice(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->UseSharedDevice = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_ForceSoftwareRenderer(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->ForceSoftwareRenderer = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_DpiScale(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->DpiScale = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_ClearColor(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->ClearColor = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_HeaderContent(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->HeaderContent = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_CustomDevice(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->CustomDevice = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   1
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   2
    L"Single", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   3
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   4
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    5, // System.ValueType
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   5
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   6
    L"Windows.UI.Color", L"",
    nullptr, nullptr, nullptr, nullptr,
    5, // System.ValueType
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   7
    L"RenderEngine.AppShell", L"",
    &ActivateType<::RenderEngine::AppShell>, nullptr, nullptr, nullptr,
    11, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   8
    L"Windows.Foundation.Size", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   9
    L"Windows.UI.Xaml.UIElement", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  10
    L"RenderEngine.Views.BasicPage", L"",
    &ActivateType<::RenderEngine::Views::BasicPage>, nullptr, nullptr, nullptr,
    11, // Windows.UI.Xaml.Controls.Page
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  11
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  12
    L"RenderEngine.DistributionType", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::RenderEngine::DistributionType>,
    4, // System.Enum
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  13
    L"Windows.UI.Xaml.Controls.Frame", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  14
    L"Windows.UI.Xaml.Input.ICommand", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  15
    L"RenderEngine.Views.LandingPage", L"",
    &ActivateType<::RenderEngine::Views::LandingPage>, nullptr, nullptr, nullptr,
    11, // Windows.UI.Xaml.Controls.Page
    1, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  16
    L"RenderEngine.Common.BindableBase", L"",
    nullptr, nullptr, nullptr, nullptr,
    17, // Windows.UI.Xaml.DependencyObject
    1, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  17
    L"Windows.UI.Xaml.DependencyObject", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    2, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  18
    L"Windows.UI.Xaml.Interop.TypeName", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    2, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  19
    L"RenderEngine.Controls.PageHeader", L"",
    &ActivateType<::RenderEngine::Controls::PageHeader>, nullptr, nullptr, nullptr,
    23, // Windows.UI.Xaml.Controls.UserControl
    2, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  20
    L"RenderEngine.Views.Distributions", L"",
    &ActivateType<::RenderEngine::Views::Distributions>, nullptr, nullptr, nullptr,
    11, // Windows.UI.Xaml.Controls.Page
    3, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  21
    L"RenderEngine.Views.MovingAverage", L"",
    &ActivateType<::RenderEngine::Views::MovingAverage>, nullptr, nullptr, nullptr,
    11, // Windows.UI.Xaml.Controls.Page
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  22
    L"Windows.UI.Xaml.Controls.ListView", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  23
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  24
    L"RenderEngine.Controls.FinancialChart", L"",
    &ActivateType<::RenderEngine::Controls::FinancialChart>, nullptr, nullptr, nullptr,
    23, // Windows.UI.Xaml.Controls.UserControl
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  25
    L"RenderEngine.Controls.NavMenuListView", L"",
    &ActivateType<::RenderEngine::Controls::NavMenuListView>, nullptr, nullptr, nullptr,
    22, // Windows.UI.Xaml.Controls.ListView
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  26
    L"Windows.UI.Xaml.Controls.ItemsControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  27
    L"Microsoft.Graphics.Canvas.CanvasDevice", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  28
    L"RenderEngine.ViewModels.DistributionViewModel", L"",
    &ActivateType<::RenderEngine::ViewModels::DistributionViewModel>, nullptr, nullptr, nullptr,
    16, // RenderEngine.Common.BindableBase
    4, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  29
    L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl", L"",
    &ActivateType<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl>, nullptr, nullptr, nullptr,
    23, // Windows.UI.Xaml.Controls.UserControl
    7, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //  30
    L"Windows.Foundation.Collections.IObservableVector`1<String>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IObservableVector<::Platform::String^>, ::Platform::String^>, nullptr, nullptr,
    -1,
    16, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    16, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      3,   //   7
      4,   //   8
      4,   //   9
      4,   //  10
      4,   //  11
      5,   //  12
      5,   //  13
      5,   //  14
      5,   //  15
      5,   //  16
      7,   //  17
      7,   //  18
      7,   //  19
      7,   //  20
      7,   //  21
      8,   //  22
      8,   //  23
      9,   //  24
      9,   //  25
     10,   //  26
     10,   //  27
     10,   //  28
     11,   //  29
     13,   //  30
     16,   //  31
     16,   //  32
     22,   //  33
     23,   //  34
     23,   //  35
     23,   //  36
     25,   //  37
     27,   //  38
     28,   //  39
     28,   //  40
     28,   //  41
     28,   //  42
     28,   //  43
     28,   //  44
     28,   //  45
     29,   //  46
     29,   //  47
     30,   //  48
     30,   //  49
     30,   //  50
     30,   //  51
     30,   //  52
     30,   //  53
     30,   //  54
     30,   //  55
     30,   //  56
     30,   //  57
     30,   //  58
     31,   //  59
};

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

const EnumValueInfo EnumValues[] =
{ 
    L"Normal", (int) ::RenderEngine::DistributionType::Normal,
    L"Log", (int) ::RenderEngine::DistributionType::Log,
    L"Exponential", (int) ::RenderEngine::DistributionType::Exponential,
    L"ChiSquared", (int) ::RenderEngine::DistributionType::ChiSquared,
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - RenderEngine.AppShell.AppFrame
    L"AppFrame",
    &GetReferenceTypeMember_AppFrame<::RenderEngine::AppShell>,
    nullptr,
    13, // Windows.UI.Xaml.Controls.Frame
    -1,
    true,  false, false,
    //   1 - RenderEngine.Common.BindableBase.Type
    L"Type",
    &GetValueTypeMember_Type<::RenderEngine::Common::BindableBase, ::Windows::UI::Xaml::Interop::TypeName>,
    nullptr,
    18, // Windows.UI.Xaml.Interop.TypeName
    -1,
    true,  false, false,
    //   2 - RenderEngine.Controls.PageHeader.HeaderContent
    L"HeaderContent",
    &GetReferenceTypeMember_HeaderContent<::RenderEngine::Controls::PageHeader>,
    &SetReferenceTypeMember_HeaderContent<::RenderEngine::Controls::PageHeader, ::Windows::UI::Xaml::UIElement>,
    9, // Windows.UI.Xaml.UIElement
    -1,
    false, true,  false,
    //   3 - RenderEngine.Views.Distributions.ViewModel
    L"ViewModel",
    &GetReferenceTypeMember_ViewModel<::RenderEngine::Views::Distributions>,
    nullptr,
    28, // RenderEngine.ViewModels.DistributionViewModel
    -1,
    true,  false, false,
    //   4 - RenderEngine.ViewModels.DistributionViewModel.RenderCommand
    L"RenderCommand",
    &GetReferenceTypeMember_RenderCommand<::RenderEngine::ViewModels::DistributionViewModel>,
    nullptr,
    14, // Windows.UI.Xaml.Input.ICommand
    -1,
    true,  false, false,
    //   5 - RenderEngine.ViewModels.DistributionViewModel.DistributionTypes
    L"DistributionTypes",
    &GetReferenceTypeMember_DistributionTypes<::RenderEngine::ViewModels::DistributionViewModel>,
    nullptr,
    30, // Windows.Foundation.Collections.IObservableVector`1<String>
    -1,
    true,  false, false,
    //   6 - RenderEngine.ViewModels.DistributionViewModel.DataType
    L"DataType",
    &GetValueTypeMember_DataType<::RenderEngine::ViewModels::DistributionViewModel, ::RenderEngine::DistributionType>,
    &SetEnumMember_DataType<::RenderEngine::ViewModels::DistributionViewModel, ::RenderEngine::DistributionType>,
    12, // RenderEngine.DistributionType
    -1,
    false, false, false,
    //   7 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.Device
    L"Device",
    &GetReferenceTypeMember_Device<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl>,
    nullptr,
    27, // Microsoft.Graphics.Canvas.CanvasDevice
    -1,
    true,  false, false,
    //   8 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.Dpi
    L"Dpi",
    &GetValueTypeMember_Dpi<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::default::float32>,
    nullptr,
    2, // Single
    -1,
    true,  false, false,
    //   9 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.UseSharedDevice
    L"UseSharedDevice",
    &GetValueTypeMember_UseSharedDevice<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Platform::Boolean>,
    &SetValueTypeMember_UseSharedDevice<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Platform::Boolean>,
    3, // Boolean
    -1,
    false, false, false,
    //  10 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.ForceSoftwareRenderer
    L"ForceSoftwareRenderer",
    &GetValueTypeMember_ForceSoftwareRenderer<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Platform::Boolean>,
    &SetValueTypeMember_ForceSoftwareRenderer<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Platform::Boolean>,
    3, // Boolean
    -1,
    false, false, false,
    //  11 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.DpiScale
    L"DpiScale",
    &GetValueTypeMember_DpiScale<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::default::float32>,
    &SetValueTypeMember_DpiScale<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::default::float32>,
    2, // Single
    -1,
    false, false, false,
    //  12 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.CustomDevice
    L"CustomDevice",
    &GetReferenceTypeMember_CustomDevice<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl>,
    &SetReferenceTypeMember_CustomDevice<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Microsoft::Graphics::Canvas::CanvasDevice>,
    27, // Microsoft.Graphics.Canvas.CanvasDevice
    -1,
    false, false, false,
    //  13 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.ClearColor
    L"ClearColor",
    &GetValueTypeMember_ClearColor<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Windows::UI::Color>,
    &SetValueTypeMember_ClearColor<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Windows::UI::Color>,
    6, // Windows.UI.Color
    -1,
    false, false, false,
    //  14 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.ReadyToDraw
    L"ReadyToDraw",
    &GetValueTypeMember_ReadyToDraw<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Platform::Boolean>,
    nullptr,
    3, // Boolean
    -1,
    true,  false, false,
    //  15 - Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl.Size
    L"Size",
    &GetValueTypeMember_Size<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, ::Windows::Foundation::Size>,
    nullptr,
    8, // Windows.Foundation.Size
    -1,
    true,  false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)
        {
            userType->AddEnumValue(
                ::Platform::StringReference(EnumValues[i].name),
                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

